### ISSUE TITLE
Include in flight work items?

### ISSUE THREAD

**Issue by kptb** [jeffpriz/ado-wait-work-time#11]
Great extension! Unfortunately for us it has one little blocker - our 'done' concept ties into a production release that may be one or more PIs into the future - these are exactly the metrics we need but we really need to be able to see it against work items in progress too.

Potential features that would help us:

- Simple: Filter to include/exclude in progress items.
- Even better, an ability to select items for a particular iteration, rather than a date range - this would allow us to review a particular iterarion without having to remeber the dates, or potentially bringing in work items from the current iteration (because it's a date backward rather than a date range.

Not sure how realistic these ideas are, but it would be great to hear from you - I know PowerBI is an option but we love your concept for a solution in-ADO.

**Comment by jeffpriz** [comment]
Thanks for the interest in this. Glad you can see that potential and the value here.

The trouble I have wrapping my head around for In-Progress is that you don't then have an actual time for the in-progress work items.  The closed items you can say "this item to X time to complete, and spent Y time in that stage" ... for in progress work items, there is not a known time to complete, and there is not a known time that a work item spent in the state.. so the numbers don't really reflect what they are meant to reflect.. The trends are the power in this right now, looking at the In Progress could give you a closer/nearer-term look at team's performance, but they aren't accurate, which I think could be more harmful.  Further the Completed date is the date we use to select work items, which I suppose is why you want to look at it through an Iteration.  I guess that it would be difficult to know what work items to select in that case.   To do what you're  suggesting would probably need to be a  different report than what I've got here.  One focused on a team that is sprinting, and measuring work items only that were part of the iteration... It could be done, but it doesn't quite fit what this particular extension is focused on.  By leaving it a little more open-ended I can serve teams that are both sprinting and doing Kanban (as teams leveraging the Kanban boards that this extension relies on may likely be using a Kanban approach). 

I guess I would say you could take this and fork it to customize it to make it meet your exact needs.   Otherwise, If anything, I would say you  could use the "Wait" for release to prod as  metric you can start to measure as well, showing how long it's taking something from Development Complete to released to production is something your team might be able to measure and improve.  Delivering Value can't happen if it's not delivered, so that could just be a large part of your overall wait.
